"""
Aplicación web para gestionar cuentas y descargar videos
"""
import os
import re
import asyncio
from datetime import datetime, timedelta
from functools import wraps
import sqlite3
import hashlib
import secrets
from flask import Flask, render_template, request, jsonify, session, redirect, url_for, send_file
from werkzeug.security import generate_password_hash, check_password_hash
import yt_dlp
from playwright.async_api import async_playwright

# Configuración
app = Flask(__name__)
app.secret_key = os.getenv('FLASK_SECRET_KEY', secrets.token_hex(32))
app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(days=7)

DOWNLOAD_DIR = os.getenv('DOWNLOAD_DIR', '/downloads')
DATABASE_PATH = os.getenv('DATABASE_PATH', 'web_users.db')

# Crear directorio de descargas si no existe
os.makedirs(DOWNLOAD_DIR, exist_ok=True)

# ===== Base de datos =====

def init_db():
    """Inicializar base de datos"""
    conn = sqlite3.connect(DATABASE_PATH)
    cursor = conn.cursor()

    # Tabla de usuarios web
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS web_users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    # Tabla de cuentas de redes sociales
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS social_accounts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            platform TEXT NOT NULL,
            platform_username TEXT NOT NULL,
            cookies TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES web_users (id),
            UNIQUE(user_id, platform)
        )
    ''')

    # Tabla de historial de descargas
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS download_history (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            url TEXT NOT NULL,
            platform TEXT NOT NULL,
            filename TEXT,
            downloaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES web_users (id)
        )
    ''')

    conn.commit()
    conn.close()

def get_db():
    """Obtener conexión a la base de datos"""
    conn = sqlite3.connect(DATABASE_PATH)
    conn.row_factory = sqlite3.Row
    return conn

# ===== Decoradores =====

def login_required(f):
    """Decorador para requerir autenticación"""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            return redirect(url_for('login'))
        return f(*args, **kwargs)
    return decorated_function

# ===== Utilidades de Twitter/X =====

async def generate_twitter_cookies(username, password):
    """
    Genera cookies de Twitter usando Playwright
    Retorna: (success: bool, cookies_str: str, error_msg: str)
    """
    try:
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=True)
            context = await browser.new_context()
            page = await context.new_page()

            # Navegar a la página de login
            await page.goto('https://twitter.com/i/flow/login', timeout=60000)
            await page.wait_for_timeout(3000)

            # Ingresar usuario
            username_input = page.locator('input[autocomplete="username"]')
            await username_input.fill(username)
            await page.wait_for_timeout(1000)

            # Click en "Next"
            next_button = page.locator('button:has-text("Next"), button:has-text("Siguiente")')
            await next_button.click()
            await page.wait_for_timeout(3000)

            # Ingresar contraseña
            password_input = page.locator('input[name="password"]')
            await password_input.fill(password)
            await page.wait_for_timeout(1000)

            # Click en "Log in"
            login_button = page.locator('button[data-testid="LoginForm_Login_Button"]')
            await login_button.click()

            # Esperar a que cargue la página principal
            try:
                await page.wait_for_url('https://twitter.com/home', timeout=30000)
            except:
                # Intentar con x.com
                await page.wait_for_url('https://x.com/home', timeout=30000)

            # Obtener cookies
            cookies = await context.cookies()

            # Convertir a formato Netscape
            cookies_str = "# Netscape HTTP Cookie File\n"
            cookies_str += "# This file is generated by Playwright. Do not edit.\n\n"

            for cookie in cookies:
                domain = cookie.get('domain', '')
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = cookie.get('path', '/')
                secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
                expiration = str(int(cookie.get('expires', -1)))
                name = cookie.get('name', '')
                value = cookie.get('value', '')

                cookies_str += f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"

            await browser.close()
            return True, cookies_str, None

    except Exception as e:
        return False, None, str(e)

# ===== Utilidades de descarga =====

def get_platform(url):
    """Detectar plataforma de la URL"""
    patterns = {
        'tiktok': r'(tiktok\.com|vm\.tiktok\.com|vt\.tiktok\.com)',
        'youtube': r'(youtube\.com|youtu\.be)',
        'twitter': r'(twitter\.com|x\.com)',
        'instagram': r'instagram\.com'
    }

    for platform, pattern in patterns.items():
        if re.search(pattern, url):
            return platform

    return None

def download_video(url, user_id, cookies_str=None):
    """
    Descargar video usando yt-dlp
    Retorna: (success: bool, filepath: str, error_msg: str, is_image: bool)
    """
    try:
        # Configuración de yt-dlp
        ydl_opts = {
            'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
            'outtmpl': os.path.join(DOWNLOAD_DIR, f'download_{user_id}_%(id)s.%(ext)s'),
            'quiet': True,
            'no_warnings': True,
        }

        # Usar cookies si están disponibles
        if cookies_str:
            cookies_file = os.path.join(DOWNLOAD_DIR, f'cookies_{user_id}.txt')
            with open(cookies_file, 'w') as f:
                f.write(cookies_str)
            ydl_opts['cookiefile'] = cookies_file

        # Descargar
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            filename = ydl.prepare_filename(info)

            # Verificar si es imagen
            is_image = filename.lower().endswith(('.jpg', '.jpeg', '.png', '.webp'))

            # Limpiar archivo de cookies temporal
            if cookies_str:
                try:
                    os.remove(cookies_file)
                except:
                    pass

            return True, filename, None, is_image

    except Exception as e:
        return False, None, str(e), False

# ===== Rutas Web =====

@app.route('/')
def index():
    """Página principal"""
    if 'user_id' in session:
        return redirect(url_for('dashboard'))
    return redirect(url_for('login'))

@app.route('/register', methods=['GET', 'POST'])
def register():
    """Registro de usuario"""
    if request.method == 'POST':
        username = request.form.get('username', '').strip()
        password = request.form.get('password', '')
        confirm_password = request.form.get('confirm_password', '')

        # Validaciones
        if not username or not password:
            return render_template('register.html', error='Usuario y contraseña son requeridos')

        if len(username) < 3:
            return render_template('register.html', error='El usuario debe tener al menos 3 caracteres')

        if len(password) < 6:
            return render_template('register.html', error='La contraseña debe tener al menos 6 caracteres')

        if password != confirm_password:
            return render_template('register.html', error='Las contraseñas no coinciden')

        # Crear usuario
        try:
            conn = get_db()
            cursor = conn.cursor()
            password_hash = generate_password_hash(password)
            cursor.execute('INSERT INTO web_users (username, password_hash) VALUES (?, ?)',
                          (username, password_hash))
            conn.commit()
            conn.close()

            return redirect(url_for('login', registered=True))

        except sqlite3.IntegrityError:
            return render_template('register.html', error='El usuario ya existe')

    return render_template('register.html')

@app.route('/login', methods=['GET', 'POST'])
def login():
    """Login de usuario"""
    if request.method == 'POST':
        username = request.form.get('username', '').strip()
        password = request.form.get('password', '')

        conn = get_db()
        cursor = conn.cursor()
        user = cursor.execute('SELECT * FROM web_users WHERE username = ?', (username,)).fetchone()
        conn.close()

        if user and check_password_hash(user['password_hash'], password):
            session['user_id'] = user['id']
            session['username'] = user['username']
            session.permanent = True
            return redirect(url_for('dashboard'))
        else:
            return render_template('login.html', error='Usuario o contraseña incorrectos')

    registered = request.args.get('registered', False)
    return render_template('login.html', registered=registered)

@app.route('/logout')
def logout():
    """Cerrar sesión"""
    session.clear()
    return redirect(url_for('login'))

@app.route('/dashboard')
@login_required
def dashboard():
    """Panel principal"""
    user_id = session['user_id']

    # Obtener cuentas configuradas
    conn = get_db()
    cursor = conn.cursor()
    accounts = cursor.execute(
        'SELECT platform, platform_username, created_at FROM social_accounts WHERE user_id = ?',
        (user_id,)
    ).fetchall()

    # Obtener historial reciente
    history = cursor.execute(
        'SELECT url, platform, filename, downloaded_at FROM download_history WHERE user_id = ? ORDER BY downloaded_at DESC LIMIT 10',
        (user_id,)
    ).fetchall()

    conn.close()

    return render_template('dashboard.html',
                          username=session['username'],
                          accounts=accounts,
                          history=history)

@app.route('/accounts')
@login_required
def accounts():
    """Gestión de cuentas de redes sociales"""
    user_id = session['user_id']

    conn = get_db()
    cursor = conn.cursor()
    accounts = cursor.execute(
        'SELECT platform, platform_username, created_at, updated_at FROM social_accounts WHERE user_id = ?',
        (user_id,)
    ).fetchall()
    conn.close()

    return render_template('accounts.html',
                          username=session['username'],
                          accounts=accounts)

@app.route('/add-account', methods=['POST'])
@login_required
def add_account():
    """Agregar cuenta de red social"""
    user_id = session['user_id']
    platform = request.form.get('platform', '').lower()
    platform_username = request.form.get('platform_username', '').strip()
    platform_password = request.form.get('platform_password', '')

    if not platform or not platform_username or not platform_password:
        return jsonify({'success': False, 'error': 'Todos los campos son requeridos'})

    if platform not in ['twitter']:
        return jsonify({'success': False, 'error': 'Plataforma no soportada'})

    # Generar cookies según la plataforma
    if platform == 'twitter':
        success, cookies_str, error_msg = asyncio.run(
            generate_twitter_cookies(platform_username, platform_password)
        )

        if not success:
            return jsonify({'success': False, 'error': f'Error al iniciar sesión: {error_msg}'})

        # Guardar en la base de datos
        try:
            conn = get_db()
            cursor = conn.cursor()
            cursor.execute('''
                INSERT OR REPLACE INTO social_accounts
                (user_id, platform, platform_username, cookies, updated_at)
                VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
            ''', (user_id, platform, platform_username, cookies_str))
            conn.commit()
            conn.close()

            return jsonify({'success': True, 'message': 'Cuenta agregada exitosamente'})

        except Exception as e:
            return jsonify({'success': False, 'error': f'Error al guardar: {str(e)}'})

    return jsonify({'success': False, 'error': 'Plataforma no implementada'})

@app.route('/delete-account', methods=['POST'])
@login_required
def delete_account():
    """Eliminar cuenta de red social"""
    user_id = session['user_id']
    platform = request.form.get('platform', '').lower()

    try:
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute('DELETE FROM social_accounts WHERE user_id = ? AND platform = ?',
                      (user_id, platform))
        conn.commit()
        conn.close()

        return jsonify({'success': True, 'message': 'Cuenta eliminada exitosamente'})

    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})

@app.route('/download', methods=['POST'])
@login_required
def download():
    """Descargar video desde la interfaz web"""
    user_id = session['user_id']
    url = request.form.get('url', '').strip()

    if not url:
        return jsonify({'success': False, 'error': 'URL es requerida'})

    # Detectar plataforma
    platform = get_platform(url)
    if not platform:
        return jsonify({'success': False, 'error': 'URL no reconocida o plataforma no soportada'})

    # Obtener cookies si existen para esta plataforma
    cookies_str = None
    if platform == 'twitter':
        conn = get_db()
        cursor = conn.cursor()
        account = cursor.execute(
            'SELECT cookies FROM social_accounts WHERE user_id = ? AND platform = ?',
            (user_id, 'twitter')
        ).fetchone()
        conn.close()

        if account:
            cookies_str = account['cookies']

    # Descargar video
    success, filepath, error_msg, is_image = download_video(url, user_id, cookies_str)

    if not success:
        return jsonify({'success': False, 'error': f'Error al descargar: {error_msg}'})

    # Guardar en historial
    try:
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute('''
            INSERT INTO download_history (user_id, url, platform, filename)
            VALUES (?, ?, ?, ?)
        ''', (user_id, url, platform, os.path.basename(filepath)))
        conn.commit()
        conn.close()
    except:
        pass  # No es crítico si falla el historial

    # Retornar archivo para descarga
    try:
        return send_file(
            filepath,
            as_attachment=True,
            download_name=os.path.basename(filepath)
        )
    finally:
        # Limpiar archivo después de 1 minuto
        import threading
        def cleanup():
            import time
            time.sleep(60)
            try:
                os.remove(filepath)
            except:
                pass

        threading.Thread(target=cleanup).start()

# ===== Inicialización =====

if __name__ == '__main__':
    # Inicializar base de datos
    init_db()

    # Ejecutar servidor
    port = int(os.getenv('WEB_PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=False)
